- stat: path="{{ mw_home }}/wlserver_10.3"
  register: mw_home_dir

- name: create ohs home directory
  file:
    path: "{{ mw_home }}"
    state: directory
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    mode: 0770
  when: not mw_home_dir.stat.exists

- name: create response file for WebLogic Server 10.3.x
  template:
    src: wls_103.xml.j2
    dest: "/tmp/wls_103.xml"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
  when: not mw_home_dir.stat.exists

- name: install oracle WebLogic Server 10.3.x
  sudo_user: "{{ oracle_user }}"
  command: "{{ java_home }}/bin/java -Djava.security.egd=file:/dev/./urandom -jar {{ wls11g_file }} -mode=silent -silent_xml=/tmp/wls_103.xml"
  when: not mw_home_dir.stat.exists
