---

- name: turn off the enterprise manager web console
  sudo_user: "{{ oracle_user }}"
  environment: oracle_user_env
  command: "{{ oracle_home }}/bin/emctl stop dbconsole"
  ignore_errors: yes

- name: create redo log directory
  file:
    mode: 0755
    path: "{{ oracle_base }}/product/redo_logs"
    state: directory
    group: "{{ oracle_group }}"
    owner: "{{ oracle_user }}"

- name: compose the oracle database ready sql
  template:
    src: em12c_pre.sql.j2
    dest: "/tmp/em12c_pre.sql"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"

- name: create redo log directory
  file:
    mode: 0755
    path: "{{ oracle_base }}/product/redo_logs"
    state: directory
    group: "{{ oracle_group }}"
    owner: "{{ oracle_user }}"

- name: check if redo_log has already been created
  stat: "path={{ oracle_base }}/product/redo_logs/log1c.rdo"
  register: redo_log_created

- name: prepare the database for em12c
  sudo_user: "{{ oracle_user }}"
  environment: oracle_user_env
  command: "cat /tmp/em12c_pre.sql | {{ oracle_home }}/bin/sqlplus / as sysdba"

- name: create middleware home directory
  file:
    mode: 0755
    path: "{{ middleware_home }}"
    state: directory
    group: "{{ oracle_group }}"
    owner: "{{ oracle_user }}"
