---
# Creating Required Operating System Groups and Users
- name: Creating Required Operating System Groups
  group: name={{ item }} state=present
  with_items:
    - "{{ oracle_group }}"
    - "{{ oracle_dba_group }}"

- name: Creating Required Operating System User
  user:
    name: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
    groups: "{{ oracle_dba_group }}"
    home: /home/{{ oracle_user }}
    shell: /bin/bash
    password: "{{ oracle_pass }}"
    append: yes



# Configuring Kernel Parameters and Resource Limits

- name: Configuring Kernel Parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    ignoreerrors: yes
  with_items:
    - { name: "kernel.shmall", value: "2097152" }
    - { name: "kernel.shmmax", value: "1050470400" }
    - { name: "kernel.shmmni", value: "4096" }
    - { name: "kernel.sem", value: "250 32000 100 128" }
    - { name: "fs.file-max", value: "6815744" }
    - { name: "fs.aio-max-nr", value: "1048576" }
    - { name: "net.ipv4.ip_local_port_range", value: "9000 65500" }
    - { name: "net.core.rmem_default", value: "262144" }
    - { name: "net.core.rmem_max", value: "4194304" }
    - { name: "net.core.wmem_default", value: "262144" }
    - { name: "net.core.wmem_max", value: "1048576" }


- name: Configuring Resource Limits
  lineinfile:
    dest: /etc/security/limits.conf
    state: present
    line: "{{ item }}"
  with_items:
    - "oracle soft nproc 16384"
    - "oracle hard nproc 16384"
    - "oracle soft nofile 4096"
    - "oracle hard nofile 65536"
    - "oracle soft stack 10240"

- name: Allow oracle to run any commands anywhere
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: "{{ item }}"
  with_items:
    - "## Allow oracle to run any commands anywhere"
    - "{{ oracle_user }}    ALL=(ALL)       NOPASSWD: ALL"

# Create Central Inventory
- name: Create the software inventory location pointer file
  lineinfile:
    dest: /etc/oraInst.loc
    create: yes
    line: "{{ item }}"
    mode: 0644
  with_items:
    - "inventory_loc = {{ oracle_inventory }}"
    - "inst_group = oracle_group"

- name: Create the inventory directory if it doesn't exist
  file:
    path: "{{ oracle_inventory }}"
    state: directory
    group: "{{ oracle_group }}"
    mode: 0770
