---
- name: install x86 package dependencies on linux 6
  yum: name={{ item }} state=present
  with_items:
#    - redhat-lsb
    - binutils-*x86_64
    - compat-libcap1-*x86_64
    - compat-libstdc++-*x86_64
    - compat-libstdc++-*i686
    - libgcc-*i686
    - libgcc-*x86_64
    - libstdc++-*x86_64
    - libstdc++-*i686
    - libstdc++-devel-*x86_64
    - sysstat-*x86_64
    - gcc-*x86_64
    - gcc-c++-*x86_64
    - glibc-*i686
    - glibc-*x86_64
    - glibc-devel-*x86_64
    - glibc-devel-*
    - libaio-*x86_64
    - libaio-devel-*x86_64

- name: create response file for BPM 11g
  template:
    src: soa11g.rsp.j2
    dest: "/tmp/soa11g.rsp"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"

- name: install bpm11g
  sudo_user: "{{ oracle_user }}"
  command: "{{ bpm11g_unzip_path }}/Disk1/runInstaller -silent -jreLoc {{ java_home }} -responseFile /tmp/soa11g.rsp -waitforcompletion"
