---
# Create a ext4 filesystem on /dev/sdb1 and check disk blocks.
- stat: path=/u01
  register: disk_mounted

- copy: src=sdb_pt.txt dest=/tmp/sdb_pt.txt
  when: not disk_mounted.stat.exists

- shell: "sfdisk /dev/sdb < /tmp/sdb_pt.txt"
  when: not disk_mounted.stat.exists

- file: mode=0755 path=/u01 state=directory
  when: not disk_mounted.stat.exists

- filesystem: fstype=ext4 dev=/dev/sdb1
  when: not disk_mounted.stat.exists

# mount the new filesystem on /u01
- mount: name=/u01 src=/dev/sdb1 fstype=ext4 state=mounted
  when: not disk_mounted.stat.exists
