- name: check if the swap has already been created
  stat:
    path: "{{ swap_file_path }}"
    get_checksum: no
    get_md5: no
  register: swap_file_created

# create swap
- name: Create swap file
  command: dd if=/dev/zero of={{ swap_file_path }} bs={{ swap_file_size }} count=1
  when: not swap_file_created.stat.exists

- name: Change swap file permissions
  file:
    path: "{{ swap_file_path }}"
    owner: root
    group: root
    mode: 0600
  when: not swap_file_created.stat.exists

- name: Make swap
  command: mkswap {{ swap_file_path }}
  when: not swap_file_created.stat.exists

- name: Add swap into /etc/fstab file
  mount: name=none src={{ swap_file_path }} fstype=swap state=present
  when: not swap_file_created.stat.exists

- name: Mount swap
  command: "swapon {{ swap_file_path }}"
  when: not swap_file_created.stat.exists
